### ISSUE TITLE
Does not work when changing on docs

### ISSUE THREAD

**Issue by gabriel-gn** [etchteam/storybook-addon-css-variables-theme#1]
#### **Description**

When changing the combo box on the "docs" tab, the theme does not switch properly.
When changing the combo box on "canvas" tab, then switch to the tab "docs", the theme applies to "docs" properly.

#### **Requirement**

Is there any way to make it work properly?
Thanks in advance!

**Comment by gavmck** [comment]
Should be! We'll try and take a look soon, but PRs are welcome.

**Comment by prodkt** [comment]
Any update on this?? Docs are incredibly important. This gets us halfway there but without the missing puzzle piece which is the theme also working in docs, it's only half done. Been a couple of months I'm assuming this isn't planned anytime soon?

**Comment by gavmck** [comment]
@prodkt @gabriel-gn This is working fine on docs as far as I can see now.
