### ISSUE TITLE
Only Loads The Second Style Sheet

### ISSUE THREAD

**Issue by mikeedwards83** [etchteam/storybook-addon-css-variables-theme#10]
I have the following in my preview.js:

```
import style1 from '!style-loader!css-loader!sass-loader!../styles/Style1.scss';
import style2 from '!style-loader!css-loader!sass-loader!../styles/Style2.scss';

import { addDecorator } from '@storybook/react';
import { withKnobs } from '@storybook/addon-knobs';
import cssVariablesTheme from '@etchteam/storybook-addon-css-variables-theme'

addDecorator(withKnobs, cssVariablesTheme);

export const parameters = { 
  cssVariables: {
    files: {
      style1,
      style2
    }
  }
}
```

When the story loads I have the dropdown select but only Style2 is used. Changes from Style1 to Style2 doesn't change anything.

To keep things simple the style sheets just change the background colours.

What am I missing here?

**Comment by gavmck** [comment]
Did you add the plugin in your `main.js` as well? https://github.com/etchteam/storybook-addon-css-variables-theme#step-1-add-the-addon

**Comment by gavmck** [comment]
Are you adding these files anywhere else in your build?

**Comment by mikeedwards83** [comment]
Thanks for the rapid response:

In the main.js we have the add-on in the addon list.

The CSS isn't imported anywhere else

**Comment by mikeedwards83** [comment]
I tried adding ?injectType=lazyStyleTag but this stops either stylesheet loading

**Comment by gavmck** [comment]
Ah I was just coming to say you need `?injectType=lazyStyleTag`

Can you show me your code with that included?

**Comment by mikeedwards83** [comment]
I have tried removing the Scss component and just using CSS. This is my preview.js:

```
import aker from '!!style-loader?injectType=lazyStyleTag!css-loader!../styles/storybook/Style1.css';

import maax from '!!style-loader?injectType=lazyStyleTag!css-loader!../styles/storybook/Style2.css';

import { addDecorator } from '@storybook/react';
import { withKnobs } from '@storybook/addon-knobs';
import cssVariablesTheme from '@etchteam/storybook-addon-css-variables-theme'


addDecorator(withKnobs, cssVariablesTheme);


export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  cssVariables: {
    files: {
      style1,
      style2
    }
  }
}
```

**Comment by gavmck** [comment]
The decorators should be added individually 

```js
addDecorator(withKnobs);
addDecorator(cssVariablesTheme);
```

**Comment by mikeedwards83** [comment]
bingo! Thanks, I took the original code from https://github.com/etchteam/storybook-addon-css-variables-theme/issues/2#issuecomment-933614359

Thanks for the rapid response and help

**Comment by gavmck** [comment]
Awesome, 2 issues with 1 fix!
