### ISSUE TITLE
Cannot get dropdown to show but changing theme key does change default theme

### ISSUE THREAD

**Issue by medissimo** [etchteam/storybook-addon-css-variables-theme#11]
Hi,

Firstly, thank you for this addon!

I am using Storybook HTML and followed your tutorial but can not seem to get the dropdown to show.

**main.js**
```
module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-storysource",
    '@etchteam/storybook-addon-css-variables-theme'
  ],
  "framework": "@storybook/html"
}
```

**preview.js**
```
import theme1 from '!!style-loader?injectType=lazyStyleTag!css-loader!../../dist/theme1/css/theme1.min.css';
import theme2 from '!!style-loader?injectType=lazyStyleTag!css-loader!../../dist/theme2/css/theme2.min.css';
import theme3 from '!!style-loader?injectType=lazyStyleTag!css-loader!../../dist/theme3/css/theme3.min.css';
import theme4 from '!!style-loader?injectType=lazyStyleTag!css-loader!../../dist/theme4/css/theme4.min.css';
import cssVariablesTheme from '@etchteam/storybook-addon-css-variables-theme'

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  cssVariables: {
    files: {
      theme1,
      theme2,
      theme3,
      theme4
    }
  }
}

export const decorators = [
  cssVariablesTheme
]
```

Passing the theme key as the theme parameter on the story does switch the default style, I am just struggling to get this dropdown to show. Any help would be greatly appreciated.

**Comment by gavmck** [comment]
Can I check if you are looking in Canvas or Docs view?

**Comment by medissimo** [comment]
Canvas view

**Comment by gavmck** [comment]
Hmm, it all _looks_ fine to me, are you able to spin up a reproduction repo?

**Comment by medissimo** [comment]
When moving the required files over to a repro the issue seems to have fixed itself. Not sure what is going on with my build but it definitely isn't an issue with the addon. Will keep adding things to repro to see what eventually breaks it. Thank you.

If anybody else does experience an issue like this it may be worth stripping things back instead of jumping the gun like me and raising an issue. Thank you for the quick replies @gavmck

**Comment by gavmck** [comment]
Huh interesting, maybe it just needed a server/storybook reboot?

Thanks for letting me know, hope you like it!

**Comment by DanWebb** [comment]
Might need to start storybook with --no-manager-cache

https://storybook.js.org/docs/react/api/cli-options/
