### ISSUE TITLE
Update design to use storybook tooltip's component

### ISSUE THREAD

**Issue by esbenjuul** [etchteam/storybook-addon-css-variables-theme#15]
Hi 
Thanks for a great addon. I have created a design update so that it uses storybook's internal components for selecting themes. I recently added a PR please consider merging if you think it brings value..
https://github.com/etchteam/storybook-addon-css-variables-theme/pull/14

**Comment by gavmck** [comment]
Thanks for the reminder, left a comment :)

**Comment by gavmck** [comment]
Out on `1.2.0` :rocket:
