### ISSUE TITLE
Does not work with sass-loader

### ISSUE THREAD

**Issue by mastermsd** [etchteam/storybook-addon-css-variables-theme#2]
Hi!

Thank you for this addon.
I would like to use this with sass-loader.

```
import light from '!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!./styles-light.scss';
import dark from '!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!./styles-dark.scss';
```
No errors appeared when I run this, yet it is not working.
Please advise. Thank you!

**Comment by gavmck** [comment]
Can you show us the rest of the file?

**Comment by mastermsd** [comment]
Sure!
```
// preview.js
import { addDecorator, addParameters } from '@storybook/angular';
import { DocsPage, DocsContainer } from '@storybook/addon-docs';
import { withKnobs } from '@storybook/addon-knobs';
import cssVariablesTheme from '@etchteam/storybook-addon-css-variables-theme'

import light from '!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!./styles-light.scss';
import dark from '!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!./styles-dark.scss';

addDecorator(withKnobs, cssVariablesTheme);

export const parameters = {
  cssVariables: {
    files: {
      kl,
      af
    }
  }
}
```

**Comment by gavmck** [comment]
Thanks! It doesn't look like you are passing the light and dark theme into the parameters

Can you try this

```
// preview.js
import { addDecorator } from '@storybook/angular';
import { withKnobs } from '@storybook/addon-knobs';
import cssVariablesTheme from '@etchteam/storybook-addon-css-variables-theme'

import light from '!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!./styles-light.scss';
import dark from '!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!./styles-dark.scss';

addDecorator(withKnobs, cssVariablesTheme);

export const parameters = {
  cssVariables: {
    files: {
      light,
      dark,
    }
  }
}
```

**Comment by gavmck** [comment]
That still looks like it's passing `kl, af` as the CSS variables files, which don't exist?

```
export const parameters = {
  cssVariables: {
    files: {
      kl, // should be light,
      af // should be dark
    }
  }
}
```

**Comment by gavmck** [comment]
Do you get the dropdown in canvas view?
Do any of the styles load?
Where are styles-light and styles-dark kept?
How are you verifying if it's working or not working?

Your comment doesn't show the correct filenames for me 🤷

**Comment by gavmck** [comment]
Is there a simple repro repo for this?

**Comment by mastermsd** [comment]
Apologies! I thought I updated it,  but it wasn't. It should be updated now.

Yes, the dropdown is showing in canvas with the options light and dark, but no styles are loaded.

**Comment by gavmck** [comment]
Ok and nothing happens when you change the drop-down?

What styles are you expecting to load? Presumably some CSS variables?

**Comment by mastermsd** [comment]
Correct, nothing happens when I change the drop-down.

Not only SASS variables are expected, but also different assets are expected. Like different font file, icons etc.
The styles are very different from each other.

**Comment by gavmck** [comment]
Can you set up a reproduction repo? I'm using this on a few projects with sass loader without issue.

**Comment by mastermsd** [comment]
Unfortunately it's a private repo, but I'll see what I can do to reproduce this in a clean new project.

**Comment by gavmck** [comment]
Thanks, if you can get a clean version set up I can have a better poke at it.

**Comment by gavmck** [comment]
@mastermsd We figured this out with @mikeedwards83 in his issue. 

Decorators need to be added individually, not in one call.

```js
addDecorator(withKnobs);
addDecorator(cssVariablesTheme);
```
