### ISSUE TITLE
Applied theme does not match or lag behind the dropdown selection

### ISSUE THREAD

**Issue by raghurana** [etchteam/storybook-addon-css-variables-theme#21]
We are using this plugin with the node_modules below
```json
"devDependencies": {
    "@etchteam/storybook-addon-css-variables-theme": "^1.2.1",
    "@storybook/addon-a11y": "^6.4.22",
    "@storybook/addon-actions": "^6.5.10",
    "@storybook/addon-docs": "^6.5.6",
    "@storybook/addon-essentials": "^6.4.20",
    "@storybook/addon-links": "^6.4.20",
    "@storybook/addons": "^6.5.10",
    "@storybook/html": "^6.4.20",
    "@storybook/theming": "^6.5.10",
    "@storybook/web-components": "^6.4.22",
```

Noticing a weird behavior where the theme selection does _not_ match with the applied theme. Theme 1 makes the text bold.
![issue-gif](https://media.giphy.com/media/n9PPLSAJdehzCnjwvJ/giphy.gif)

**Comment by pixelrabbit** [comment]
I am also seeing this behavior.

**Comment by duncanhunter** [comment]
I am also facing this and only used in the development environment at the moment and blocked from releasing with this ability.

Be great to get some help to fix it.

**Comment by keerthuakrish** [comment]
Hi @gavmck , Would you be able to help resolving this issue?

**Comment by gavmck** [comment]
Can anyone provide a reproduction repo? This is working OK at our end.

**Comment by duncanhunter** [comment]
@gavmck I will try replicate it in a public repo and share here tomorrow. Thanks for the help.

**Comment by gavmck** [comment]
Thanks!

**Comment by duncanhunter** [comment]
@gavmck, here is a link to the repo in GitHub and the GitHub pages that replicates the issue.
- GitHub repo: https://github.com/duncanhunter/stencil-demo
- GitHub pages: https://duncanhunter.github.io/stencil-demo/?path=/story/mybutton--default-story

**Comment by gavmck** [comment]
@duncanhunter Thanks! It looks like the theme switching is working, but the dropdown label/selected is not updating correctly. I'll take a look today.

**Comment by duncanhunter** [comment]
That is what it feels like to us just a cosmetic issue.

Thanks again.

**Comment by gavmck** [comment]
@duncanhunter That was very helpful. Fixed on 1.3.3 :)

**Comment by duncanhunter** [comment]
Awesome thank you!

**Comment by keerthuakrish** [comment]
@gavmck @duncanhunter  Thank you so much for helping with this! Really appreciate your timely help.
