### ISSUE TITLE
Core functional doesn't work with postcss

### ISSUE THREAD

**Issue by fenreys** [etchteam/storybook-addon-css-variables-theme#3]
Greetings, @gavmck! i'm asking your attention and help
---
1) I added plug-in in my project using your tutorial
- ![0](https://user-images.githubusercontent.com/70163026/141647016-d65bcd10-639f-4fd5-8526-b23a968709a1.png)
with postcss-loader
- ![5](https://user-images.githubusercontent.com/70163026/141647551-7a58bddc-5cbf-495b-aed4-38aa93fc64a9.png)
without it
- ![1](https://user-images.githubusercontent.com/70163026/141646945-5a4b1980-79ef-4caa-b467-f8df267b2fac.png)

Unfortunatly, storybook started with errors, i found soluttion to my problem, after that: style, css 'n' postcss-loaders versions were downgreaded, and now storybook starts with additional options on tools-bar contained my themes, but..
- ![2](https://user-images.githubusercontent.com/70163026/141647080-6b2514c8-1040-4272-8b11-413947613b2c.png)

anyway css variables are just don't working
- ![3](https://user-images.githubusercontent.com/70163026/141647169-a6be112a-7f6c-48b0-9027-7ae6f3513f13.png)

 Thanks in advance!

**Comment by gavmck** [comment]
Why are the CSS variables inside classes?
That will scope them to the class, which is not added by this plugin.

Try putting them inside a `:root` instead.

**Comment by fenreys** [comment]
> Why are the CSS variables inside classes? That will scope them to the class, which is not added by this plugin.
> 
> Try putting them inside a `:root` instead.

Thanks a lot! Everything works, have a nice day c:

**Comment by gavmck** [comment]
Awesome, glad it worked! Hope you have fun with the plugin 😎
