### ISSUE TITLE
Theme fallsback to default when a prop is change in stories

### ISSUE THREAD

**Issue by AlexMargk2112** [etchteam/storybook-addon-css-variables-theme#33]
Recently i added a default theme for some stories. I realized that when switching themes and updating some controls the theme falls back to the default theme.

```
export default {
  title: 'Molecules/A-Thing',
  component: AThingComp,
  args: {
  },
  argTypes: {

  },
  parameters: {
    cssVariables: {
      theme: 'ATheme',
    },
  },
}
```

Also i notice that in cookies is the correct theme.

Im not sure if it happened also to another person.

**Comment by igataciertocom** [comment]
I have the same Issue.

**Comment by DanWebb** [comment]
Is this issue only present when [setting a specific theme for a story](https://github.com/etchteam/storybook-addon-css-variables-theme#set-a-specific-theme-for-a-story)?

**Comment by gavmck** [comment]
Closing as stale
