### ISSUE TITLE
StyleLoader and CssLoader are not defined if webpack5 is used

### ISSUE THREAD

**Issue by andtherand** [etchteam/storybook-addon-css-variables-theme#34]
Both modules (style-loader and css-loader) are not found when starting storybook with webpack 5.
It seems that this plugin only works with webpack 4 out of the box. Maybe this should be part of the docs.

I got it working by adding those two modules as devDependencies of my instance of storybook.

**Comment by DanWebb** [comment]
Fixed in https://github.com/etchteam/storybook-addon-css-variables-theme/commit/0e8440787a815912a51bef7413f92cc817e74852 hopefully this is clearer now 🤞
