### ISSUE TITLE
Not compatible with Storybook v7

### ISSUE THREAD

**Issue by goldst** [etchteam/storybook-addon-css-variables-theme#38]
Hello there, once more thanks for the addon. We're still big fans of it.

We are in the process of moving from Storybook 6 to Storybook 7 beta and would like to keep switching themes.

Storybook-addon-css-variables-theme does not load themes in the current prerelease of Storybook 7.

The reason is that the channel API doesn't work anymore. Importing `useChannel` from the new location doesn't seem to fix it.

This can be reproduced by running `npx storybook@next upgrade --prerelease` on an existing Storybook (not this repository), accepting all migrations, and installing this addon. I would appreciate it if you could try to reproduce it because I see there already was a Storybook 7-related PR and nobody mentioned that it wasn't working.

I pushed a fix to [our fork](https://github.com/hatch-dev/storybook-addon-css-variables-theme/tree/feat/storybook-7) that replaces the Storybook API calls with iframe message events. This works with both Storybook 6 and 7. If you can reproduce the problem above, I can create a PR. For now, it is incomplete though because in sb7 there are cases in which it only works after reloading.

**Comment by jonniebigodes** [comment]
I'm one of the Storybook maintainers. I focus primarily on documentation and community outreach. Just wanted to follow up on this issue letting you know that the Storybook API for building addons is currently being updated to factor in the changes introduced by the upcoming 7.0 release. If you're interested in making the required changes to help the community from benefiting from using your addon, we've prepared an abridged guide for the required changes [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040), and if you have any questions or issues, please reach out to us in the #prerelease channel in our [Discord Server](https://discord.gg/storybook). 

Hope you have a great day!

Stay safe

**Comment by johantor** [comment]
Added a fix for this, only change needed was the named import. Running this on 7.0.0-beta.48 locally. 
#40

**Comment by goldst** [comment]
Thanks @johantor, I updated our storybook and all official addons from 7.0.0-beta.21 to 7.0.0-beta.49 and can confirm that your change to named import now fixes the problem!

**Comment by JReinhold** [comment]
Hey @johantor and @DanWebb, Storybook v7.0.0 is out! It's only on the `next` tag for now, but it's still targetable with the `^7.0.0` semver range, so you should be able to develop against it with no dependency issues.

It seems like you've already sorted out v7 support, but it would be a great help to users if you would upgrade the dependencies in [`package.json`](https://github.com/etchteam/storybook-addon-css-variables-theme/blob/master/package.json#L47-L87) from `^7.0.0-beta.49` to just `^7.0.0`.

If you hit any issues with v7, we've written a migration guide for addon authors [here](https://github.com/storybookjs/storybook/blob/norbert/add-addon-migration-guide/MIGRATION.md?rgh-link-date=2023-03-31T20%3A36%3A23Z#specific-instructions-for-addon-creators) and [here](https://chromatic-ui.notion.site/Addon-migration-for-Storybook-7-002f2f627c1d470298ca94894ab8a040).

You're also free to reach out to us in the #prerelease channel on our [Discord Server](https://discord.gg/storybook) and we'll happily help you out!

cc @ndelangen
