### ISSUE TITLE
Need to change theme programmatically using a button inside a story

### ISSUE THREAD

**Issue by madanankit** [etchteam/storybook-addon-css-variables-theme#41]
Is there a way to set theme programmatically using a button inside a story

**Comment by DanWebb** [comment]
No, but you could [set a specific theme for a story](https://github.com/etchteam/storybook-addon-css-variables-theme#set-a-specific-theme-for-a-story) using story parameters.

Out of interest what is the use case for including a separate button when the toolbar button is always visible on the story?

**Comment by gavmck** [comment]
Closing as stale
