### ISSUE TITLE
Making addon work with Sass Glob Importer

### ISSUE THREAD

**Issue by pauloguerraf** [etchteam/storybook-addon-css-variables-theme#5]
Hi,

I am currently running on an issue when trying to import my scss files, since they have imports to other files and directories. 
Storybook's main.js is using globImporter ([](https://npm.io/package/node-sass-glob-importer)) to import directories that contian scss files, but when using the addon it is throwing the following error

```
SassError: File to import not found or unreadable: components/**/*.
        on line 15 of src/scss/light.scss
>> @import "components/**/*";
```

**ligh.scss** file looks like this

```

$theme: "light";

@import
"../../node_modules/sass-mq/mq",
"core/reset",
"core/variables",
"core/colorpalette",
"core/typography",
"core/swiper",
"core/global";

//Components
@import "components/**/*";

//Modules
@import "modules/**/*";

// Placeholders
@import "placeholders/**/*";
```

this is how **.storybook/preview.js** looks:

```
import { addDecorator } from '@storybook/html';
import light from '!!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!../src/scss/light.scss'
import dark from '!!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!../src/scss/dark.scss'
import cssVariablesTheme from '@etchteam/storybook-addon-css-variables-theme'


export const parameters = {
  cssVariables: {
    files: {
      light,
      dark,
    }
  }
};

export const decorators = [
  cssVariablesTheme
];
```

and **.storybook/main.js:**

```
module.exports = {
    stories: [path.resolve(dir.stories, './**/*.stories.@(js|mdx)')],
    addons: [
      '@storybook/addon-links',
      '@storybook/addon-essentials',
      '@storybook/addon-a11y',
      '@etchteam/storybook-addon-css-variables-theme'
    ],
    webpackFinal: async (config, { configType }) => {
      config.module.rules.push({
        test: /\.scss$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              sourceMap: true
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                ident: 'postcss',
                plugins: {
                  autoprefixer: {}
                }
              },
              sourceMap: true
            }
          },
          {
            loader: 'resolve-url-loader',
            options: {
              root: path.resolve(dir.paths.srcStatic)
            }
          },
          {
            loader: 'sass-loader',
            options: {
              sassOptions: {
                importer: globImporter()
              }
            }
          }
        ],
        include: path.resolve(dir.paths.srcStyles)
      });
  }
}

```

any tip or advice on how to fix this issue would be greatly appreciated.
thank you in advance for your help

**Comment by gavmck** [comment]
The inline import syntax removes all the default webpack settings for that filetype.

You need to add the globimporter in your import.

Not sure how to do it off the top of my head though. Let me know if you figure it out, otherwise I can take a look in a few hours.

**Comment by pauloguerraf** [comment]
Thank you, Gavyn. I'll take a look.  Should be something along these lines, right?

![image](https://user-images.githubusercontent.com/1149371/150568263-3dc78854-df2d-455c-afd4-2f5ed983b588.png)

**Comment by gavmck** [comment]
Yep, that's the one! The important one for this plugin is is the lazyStyleTag setting on style-loader, then you just need to figure out how to pass it the bits of your webpack loader you need to get globImporter working.

**Comment by pauloguerraf** [comment]
Thank you, Gavyn. I wasn't able to make node-sass-glob-importer work with inline loaders. Seems it is kind of outdated (last published 3 years ago) and kept throwing errors after figuring the right import syntax. 

But well, I went ahead and replaced all my directory imports with file-by-file imports and now your addon is working smoothly. 

Thank you very much for all your help 💯

**Comment by gavmck** [comment]
> Thank you, Gavyn. I wasn't able to make node-sass-glob-importer work with inline loaders. Seems it is kind of outdated (last published 3 years ago) and kept throwing errors after figuring the right import syntax.
> 
> But well, I went ahead and replaced all my directory imports with file-by-file imports and now your addon is working smoothly.
> 
> Thank you very much for all your help 💯

Ah that's a shame it didn't work with the glob importer, but that's great you got it working!

**Comment by pauloguerraf** [comment]
yeah, quite a bummer. please update this issue if you ever get it working with something like directory imports for sass files 🙂. thank you again, Gavyn!

**Comment by pauloguerraf** [comment]
I made some progress today. It at least recognize the importer option now. This is the import line I am using

`import light from '!!style-loader?injectType=lazyStyleTag!css-loader!sass-loader?{sassOptions:{"importer":"globImporter"}}!../src/scss/light.scss'
`

unfortunately, seems to be an issue with it not recognizing globImporter and I keep getting the following error:

`node_modules/sass-loader/dist/utils.js:109
      return importer.apply(this, args);
                      ^

TypeError: importer.apply is not a function`


any clue on what I could be missing?

**Comment by gavmck** [comment]
You're passing a string of `"globImporter"`, not the `globImporter` object/import/variable/thing.
That's where I got a bit stuck, not sure how to pass that in using inline imports like this.

**Comment by pauloguerraf** [comment]
Found a solution using [](https://www.npmjs.com/package/webpack-import-glob-loader)

my import line now looks like this. Everything working with global imports in my .scss files

` import light from '!!style-loader?injectType=lazyStyleTag!css-loader!sass-loader!import-glob-loader!../src/scss/light.scss';
`

thank you for all your help, Gavin. Awesome addon!

**Comment by gavmck** [comment]
Oh, neat!
