### ISSUE TITLE
CSS Variables Theme does not work on Storybook 8.0.0

### ISSUE THREAD

**Issue by aldipaglia** [etchteam/storybook-addon-css-variables-theme#60]
I'm working on a Storybook project that was using `V. 6.5.13`, and now we are updating it to the `8.0.0 version`. 
We were using `storybook-addon-css-variables-theme`, but during the upgrade, we got this error from the doctor:
![Screenshot 2024-03-18 at 5 28 46 PM](https://github.com/etchteam/storybook-addon-css-variables-theme/assets/50784650/a73d3244-b531-49b1-ab93-22e31126caba)
No document explains if the package will work on the latest versions of Storybook.

Also, I followed the docs to use the package on the latest version of Storybook but when I ran `npm run storybook` I got this error:
![Screenshot 2024-03-18 at 5 35 25 PM](https://github.com/etchteam/storybook-addon-css-variables-theme/assets/50784650/7e25dbca-56a8-4659-a4c7-2db01a702d70).

Any help will be appreciated :)

**Comment by pkyeck** [comment]
Are there any plans to update the plugin for v8?

**Comment by hamza14khan** [comment]
@aldipaglia did ye try anything to fix this?
