### ISSUE TITLE
Compatibility issues with Storybook v8.2.6

### ISSUE THREAD

**Issue by eliasmohsengrenvald** [etchteam/storybook-addon-css-variables-theme#70]
Unfortunately, the theme switcher no longer shows up in Storybook v8.2.6, whereas it used to work fine up until v8.0.9

**Comment by ella-etch** [comment]
@eliasmohsengrenvald Hey! We’ve been having a look at this but haven’t been able to reproduce the issue. Do you have a minimal reproduction you could send?

**Comment by eliasmohsengrenvald** [comment]
Hi @ella-etch ,
I will wait for Storybook v8.3.0 and test it again and will try to make a minimal reproduction if I see that's still broken, will keep you posted

**Comment by eliasmohsengrenvald** [comment]
Hi @ella-etch ,
I just made a minimal reproduction with the v3 and I can actually see that the theme switcher is showing up on the toolbar, however, it doesn't really swap the theme, or perhaps I'm doing it wrong?
https://github.com/eliasmohsengrenvald/css-variable-theme-storybook

**Comment by eliasmohsengrenvald** [comment]
Hi @ella-etch ,
Thanks a lot for sharing that and your quick answer, we did have something similar, however tweaking it to your recommended solution did the trick, and got it working! 🙏  so I close this ticket
