### ISSUE TITLE
Switch css via url param

### ISSUE THREAD

**Issue by ulrichgreen** [etchteam/storybook-addon-css-variables-theme#9]
Hi there.

Awesome addon!

Would be nice if I could use it when handing out links to stakeholders, like:
mydomain.com?iframe.html?id=story-id&viewMode=story&**theme=mytheme**

**Comment by gavmck** [comment]
That would be awesome! 
We'll try and get to it, but PRs are very welcome.

**Comment by JungowskiWojciech** [comment]
Hello, 
Any news about this feature?

**Comment by gavmck** [comment]
Out on 1.5.0 @JungowskiWojciech @ulrichgreen, sorry it took a while!
